name: _flutter_map_sld_workspace
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  - packages/flutter_map_sld
  - packages/flutter_map_sld_io
  - packages/flutter_map_sld_flutter_map
